---
title: "GT Cups"
author: "gidddybb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
tags:
  - Teams
  - zz3
  - Detailed
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::read_chunk(paste0(rprojroot::find_rstudio_root_file(), "/content/project/common_project_code.R"))

```


```{r setup, include=FALSE}
```


```{r cleancalculate, echo=FALSE, message=FALSE, warning=FALSE}
```

The graph below shows the cup progress over time of Zig-Zag GT. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}

all_matches %>%
  filter(teamname=="GT", !is.na(zz_cups_before)) %>%
  ggplot(aes(x=match_number, y=zz_cups_before)) +
  geom_point() +
  geom_line() +
  geom_label_repel(size=2, aes(label=opposition))+
  theme_bw() +
  labs(y="cups")
```

The graph below shows the cup progress over time of Zig-Zag GT relative to the other Zig-Zag teams. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}

all_matches %>%
  ggplot(aes(x=round_number, y=zz_cups_before)) +
  geom_line(size=1, aes(colour=teamname)) +
  theme_bw() +
  labs(y="cups")
```

