---
title: "Team Results"
author: "giddybb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
summary: Team average score across events
output: html_document
tags:
- Team
- Basic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googledrive)
library(googlesheets4)
library(tidyverse)
library(ggrepel)
library(arm)
library(formattable)
#library(rstanarm)
library(kableExtra)
drive_auth("gidon.d.cohen@gmail.com")
sheets_auth(token=drive_token())


zz_matches <- read_sheet("1ftRMXTRL84SO-eedX8EIof8i_5C64qemwskffr8DUXA", sheet=3)
zz_results <- read_sheet("1ftRMXTRL84SO-eedX8EIof8i_5C64qemwskffr8DUXA", sheet=4, col_types="c", skip = 3) %>%
  mutate(team="Zig-Zag Racers")

gs_matches <- read_sheet("1VfIqaB--8Y-pF06zp1KEBrTJyX1A_33XKG30n38Da14", sheet=3)
gs_results <- read_sheet("1VfIqaB--8Y-pF06zp1KEBrTJyX1A_33XKG30n38Da14", sheet=4, col_types="c", skip = 3) %>%
  mutate(team="GreasySpanner")


cb <- function(x) {
  range <- max(abs(x))
  width <- round(abs(x / range * 50), 2)
  ifelse(
    x > 0,
    paste0(
      '<span style="display: inline-block; border-radius: 2px; ', 
      'padding-right: 2px; background-color: lightgreen; width: ', 
      width, '%; margin-left: 50%; text-align: left;">', x, '</span>'
    ),
    paste0(
      '<span style="display: inline-block; border-radius: 2px; ', 
      'padding-right: 2px; background-color: lightpink; width: ', 
      width, '%; margin-right: 50%; text-align: right; float: right; ">', x, '</span>'
    )
  )
}
```


```{r cleancalculate, echo=FALSE, message=FALSE, warning=FALSE}
zz_results <- zz_results %>%
    mutate(PlayerTeam=paste0(Players, "(", team, ")")) 

zz_matches <- zz_matches %>%
  mutate(event_round=tolower(event_round),
         event_std = tolower(event))

zz_res_long <- zz_results %>%
  pivot_longer(-c(Players, PlayerTeam, GP, Current, team), names_to="event_round", values_to = "score") %>%
  mutate(event_round=tolower(event_round))%>%
  inner_join(zz_matches, by="event_round") %>%
  mutate(matches_ago = max(match_number) + 1 - match_number)

gs_results <- gs_results %>% 
    mutate(PlayerTeam=paste0(Players, "(", team, ")")) 

gs_matches <- gs_matches %>%
  mutate(event_round=tolower(event_round),
         event_std = tolower(event))

gs_res_long <- gs_results %>%
  pivot_longer(-c(Players, PlayerTeam, GP, Current, team), names_to="event_round", values_to = "score") %>%
  mutate(event_round=tolower(event_round))%>%
  inner_join(gs_matches, by="event_round") %>%
  mutate(matches_ago = max(match_number) + 1 - match_number)

results <- bind_rows(zz_results, gs_results)

res_long <- bind_rows(zz_res_long, gs_res_long) %>%
  group_by(event_round) %>%
  mutate(
    GP=as.numeric(GP),
    std_GP = (GP-mean(GP, na.rm=TRUE))/sd(GP, na.rm=TRUE),
    score = as.numeric(score),
    event_sd = sd(score, na.rm=TRUE), 
         event_mu = mean(score, na.rm=TRUE),
         std_score = (score-event_mu)/event_sd,
    has_zig_zag = sum(team=="Zig-Zag Racers"&!is.na(score), na.rm=TRUE)>0,
    has_gs = sum(team=="GreasySpanner"&!is.na(score), na.rm=TRUE)>0,
    team_type = ifelse(has_zig_zag&has_gs, "both", ifelse(has_zig_zag, "zz1 only", "gs only")))
  

gp_sd = sd(as.numeric(results$GP), na.rm=TRUE)
gp_mu = mean(as.numeric(results$GP), na.rm=TRUE)
score_sd = sd(as.numeric(res_long$score), na.rm=TRUE)
score_mu = mean(as.numeric(res_long$score), na.rm=TRUE)
```


## Team Average Scores

```{r, echo=FALSE, message=FALSE}
events <- gs_matches %>%
  group_by(event, event_std) %>%
  summarize(no = min(match_number)) %>%
  arrange(no) %>%
  mutate(event_id = row_number())

```


```{r, echo=FALSE, message=FALSE}


event_std<- res_long %>% 
  group_by(event, round, event_round) %>%  summarize(
    event_sd = sd(score, na.rm=TRUE), 
    event_mu = mean(score, na.rm=TRUE),
    has_zig_zag = sum(team=="Zig-Zag Racers"&!is.na(score), na.rm=TRUE)>0,
    has_gs = sum(team=="GreasySpanner"&!is.na(score), na.rm=TRUE)>0,
    team_type = ifelse(has_zig_zag&has_gs, "both", ifelse(has_zig_zag, "zz1 only", "gs only"))) %>%
  mutate(event_std = tolower(event)) %>%
  left_join(events) %>%
  arrange(event_id, round) %>%
  ungroup() %>%
  mutate(event_round_id = row_number())


event_byteam<- res_long %>% 
  group_by(event, round, event_round, team) %>%  
  summarize(
    event_sd = sd(score, na.rm=TRUE), 
    event_mu = mean(score, na.rm=TRUE)) %>%
  mutate(event_std = tolower(event)) %>%
  left_join(events) %>%
  arrange(event_id, round) %>%
  ungroup() %>%
  left_join(event_std %>% dplyr::select(event, round, event_round_id))%>%
  mutate(rd = round, 
         event_label = ifelse(rd==1, event, NA_character_))

```

```{r, echo=FALSE, message=FALSE}
event_byteam %>%
  mutate(event = factor(event, levels = events$event[order(events$event_id)])) %>%
ggplot(aes(event_round_id, event_mu, colour=team)) +
  facet_wrap(~event, scales="free_x")+
  geom_point() +
  geom_line(aes(colour=team)) +
  labs(x=NULL,
       y="Average Score") +
  scale_x_continuous(labels=NULL, breaks=waiver()) +
  theme_bw()
```

