---
title: "Zig-Zag Cups: All Teams"
author: "gidddybb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
summary: Cup progress for all Zig-Zag teams (with top and top 100 trajectory).
tags:
  - Teams
  - zz1
  - zz2
  - zz3
  - Basic
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::read_chunk(paste0(rprojroot::find_rstudio_root_file(), "/content/project/common_project_code.R"))

```


```{r setup, include=FALSE}
```


```{r cleancalculate, echo=FALSE, message=FALSE, warning=FALSE}
```

The graph below shows the cup progress over time of the three Zig-Zag teams. The lines in black show the trophies of the rank 1 and the rank 100 teams respectively.

```{r, echo=FALSE, message=FALSE, warning=FALSE}

all_matches %>%
  ggplot(aes(x=round_number, y=zz_cups_before)) +
  geom_line(data=topscores, aes(y=Rank1Cups), na.rm=TRUE)+
  geom_line(data=topscores, aes(y=Rank100Cups), na.rm=TRUE) +
  #geom_point(aes(colour=teamname)) +
  geom_line(size=1, aes(colour=teamname)) +
  theme_bw() +
  labs(y="cups")
```

